
name: Generate ASCII Artwork
'on': push
jobs:
  Cowsays:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install cowsays
        run: sudo apt-get install cowsay -y
      - name: Execute cowsay
        run: cowsay -f lion "Run for cover, I am lion" >> lion.txt
      - name: Test File exist
        run: grep -i "lion" lion.txt
      - name: Read File
        run: cat lion.txt
      - name: List Repo Files
        run: ls -ltra
